---
apiVersion: v1
kind: Secret
metadata:
  name: bgg-app-secret
type: Opaque
data:
  BGG_DB_PASSWORD: Y2hhbmdlaXQ=
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: bgg-app-deploy
    labels:
        name: bgg-app-deploy
strategy:
    type: RollingUpdate
    rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
spec:
    replicas: 3
    selector:
        matchLabels: 
            name: bgg-app-pod
    template:
        metadata:
            name: bgg-app-pod
            labels:
                name: bgg-app-pod

    # namespace: myns
        spec:
            containers:
                - name: bgg-app-container
                  image: stackupiss/bgg-backend:v2
                  imagePullPolicy: IfNotPresent
                  env:
                      - name: BGG_DB_USER
                        value: 'root'
                      - name: BGG_DB_HOST
                        value: 'bgg-db-svc.bggns.svc.cluster.local'
                  envFrom:
                    - secretRef: 
                        name: bgg-app-secret
                  ports:
                      - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
    name: bgg-app-svc
    labels:
        name: bgg-app-svc
spec:
    type: NodePort
    selector:
        name: bgg-app-pod
    ports:
        - port: 8080
          targetPort: 3000
---