apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
    name: bgg-app-hpa
    labels:
        name: bgg-app-hpa
spec:
    minReplicas: 1
    maxReplicas: 4
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: bgg-app-deploy
    metrics:
        - type: Resource
          resource:
              name: cpu
              target:
                  type: Utilization
                  averageUtilization: 150
        - type: Resource
          resource:
              name: memory
              target:
                  type: Utilization
                  averageUtilization: 90
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
    name: bgg-app-hpa-2
    labels:
        name: bgg-app-hpa-2
spec:
    minReplicas: 1
    maxReplicas: 4
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: bgg-app-deploy-2
    metrics:
        - type: Resource
          resource:
              name: cpu
              target:
                  type: Utilization
                  averageUtilization: 150
        - type: Resource
          resource:
              name: memory
              target:
                  type: Utilization
                  averageUtilization: 90