apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
    - "../../Day 2/demo/"

namePrefix: kuz-
nameSuffix: -k8s

commonLabels:
    deployDate: "Mar 31 2022"

replicas:
    - name: dov-deploy
      count: 1